version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    networks:
      - front-tier
      - back-tier

  backend:
    build:
      context: ./backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tracker-db
    depends_on:
      - "db"
    ports:
      - "8080:8080"
    volumes: 
      - :/maven_cache
    networks:
      - front-tier
      - back-tier

  db:
    build:
      context: ./db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:
  maven_cache:

networks:
  front-tier:
  back-tier:
